### ISSUE TITLE
--profiles option does not work anymore

### ISSUE THREAD

**Issue by vbouchet31** [acquia/acsf-tools#113]
acsf-tools-ml command has a --profiles option to filter the sites to execute the command on. It seems to not work anymore.

To determine the profile, the system currently does the following:
```
$site_settings_filepath = 'sites/g/files/' . $details['name'] . '/settings.php';
  if (!empty($profiles) && file_exists($site_settings_filepath)) {
    $site_settings = @file_get_contents($site_settings_filepath);
    if (preg_match("/'install_profile'] = '([a-zA-Z_]*)'/", $site_settings, $matches)) {
```

On the factory I am currently testing the command, this file is only containing:
```
<?php

require('/var/www/html/<subscription>.<environment>/docroot/sites/g/settings.php');

```
so the profile detection is failing.

**Comment by vbouchet31** [comment]
The profile option has been removed from the 10.x branch.

**Comment by sdelbosc** [comment]
In case you want to keep that feature then maybe this would not be too expensive:
drush -l mysite sqlq 'select data from config where name="core.extension" limit 1' | grep -Po 's:7:"profile";s:[0-9]+:"[^"]+";' | cut -d'"' -f4
