### ISSUE TITLE
Drush 10: ACSF-tools commands not working

### ISSUE THREAD

**Issue by gauravmanerkar** [acquia/acsf-tools#116]
Hi,

ACSF tools v10 dev branch has issues. ACSF tools commands are not working for me. I am using drush v10.3.5.

cset command not working with acsf-tools-ml
No drush messages with acsf-tools-ml command

**Comment by vbouchet31** [comment]
Hi @manerkargaurav,

Do you have more details? What is the exact command you are running? The result? Drupal version? acsf-tools version/commit?

**Comment by gauravmanerkar** [comment]
@vbouchet31 

Drupal version is 8.9.7
BLT version is 11.6.0
I have checked with latest 10.x-dev code

Issues: 

Commands like cset are not working with acsf-tools-ml.
See image below.
![imageedit_15_6478848962](https://user-images.githubusercontent.com/54015848/97154880-7fb67b00-179a-11eb-8bc9-d3c395f2ed2c.png)

No messages displaying for commands like cr, updb.
See image below.
![imageedit_18_4506255272](https://user-images.githubusercontent.com/54015848/97155197-fbb0c300-179a-11eb-9213-ad2c132ca534.png)

**Comment by vbouchet31** [comment]
Thanks for the quick reply.

I will give a look to your example. Cset (and globally commands with arguments, ...) has been an issue since drush8 (I think).

Regarding the second one, I am aware of it but not 100% the reason. I will give a look as well.

**Comment by vbouchet31** [comment]
Hi,

I will raise a PR soon for the updb part. For some reason this command is logging some message in the errorOutput even notice/success.

Regarding the cset command, I ran the following `$ drush acsf-tools-ml cset "'user.settings' 'verify_mail' 'true'"` with success.

**Comment by gauravmanerkar** [comment]
Hi, 

Messages are not displaying for cache rebuild command as well..

`drush acsf-tools-ml cr`

**Comment by vbouchet31** [comment]
I think my "fix" for updb will fix this one as well. Let me raise the PR.

**Comment by vbouchet31** [comment]
Hey @manerkargaurav , I forgot to update here but I merged some change in the 10.x branch. Please let me know if it helps.

**Comment by gauravmanerkar** [comment]
Hi @vbouchet31 ,
i see some of the commands like updb, cr is supported now, but commands like which i have mentioned on below req are not working.

https://github.com/acquia/acsf-tools/issues/133

**Comment by gauravmanerkar** [comment]
Closing this issue ticket as the commands are working after adding quotes.

**Comment by mashirulcts** [comment]
@vbouchet31 Could you please let me know how we can set multiple key values using sfml and cset?

Basically I wanted to run below command along with sfml:

`drush @alias config:set editor.editor.rich_text \? '{ "dependencies": { "module": [ "ckeditor5" ] }, "editor": "ckeditor5", "settings": { "toolbar": { "items": [ "bold", "italic", "link", "bulletedList", "numberedList", "heading", "subscript", "superscript", "insertTable" ] } } }' --input-format=yaml`
