### ISSUE TITLE
Drupal 9 support

### ISSUE THREAD

**Issue by marvil07** [acquia/acsf-tools#118]
The main readme point to install acsf-tools either at (a) `~/.drush/` or (b) at the project.
For (b) a change seems to be needed to be compatible with Drupal 9 dependencies.

The problem:
* It seems like current versions of acsf-tools, i.e. `8.x-dev`, `9.x-dev`, and `10.x-dev`, depend on symfony/yaml `3.x`, e.g. https://github.com/acquia/acsf-tools/blob/10.x-dev/composer.json#L23
* Drupal 9 core depends on symfony/yaml `4.x`, e.g. https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/composer.json#L32

This naturally result on not being able to install acsf-tools on a Drupal 9 project.

The best case scenario is to support symfony/yaml in both `3.x` and `4.x` versions.

I see the use is minimal:

    $ git grep Yaml
    AcsfToolsUtils.php:use Symfony\Component\Yaml\Yaml;
    AcsfToolsUtils.php:    $yaml = Yaml::parse(file_get_contents($path . '/acsf_tools_config.yml'));

Hence, supporting both should be OK.
There are no breaking changes between those versions, e.g. compare https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Yaml/Yaml.php#L80 and https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Yaml/Yaml.php#L76

I will add a related PR against 9.x-dev, since I see that 10.x-dev is still not ready as per https://github.com/acquia/acsf-tools/issues/115#issuecomment-716400970 to support both `3.x` and `4.x`, but that same change may be applied/cherry-picked to other branches too.

**Comment by sdelbosc** [comment]
Merged this on 9.x with https://github.com/acquia/acsf-tools/pull/119 and 10.x with https://github.com/acquia/acsf-tools/pull/125
