### ISSUE TITLE
Drush commands not working

### ISSUE THREAD

**Issue by gauravmanerkar** [acquia/acsf-tools#133]
Hello,

I am using acsf tools v10, drush 10, drupal 8.9 and blt v11. Project with acsf
I see commands like`drush @be.01test acsf-tools-ml  "cset -y cdn.settings status 0"` are throwing error with  acsf tools v10 which was working fine with earlier version of tool.

**Comment by vbouchet31** [comment]
Hi,

As per [this comment](https://github.com/acquia/acsf-tools/issues/116#issuecomment-716563968), I think the appropriate command is `drush acsf-tools-ml cset "'cdn.settings' 'status' '0'"`. I am not sure the -y option is needed in that case.

**Comment by gauravmanerkar** [comment]
hi @vbouchet31 
after adding quotes its working. I am closing this ticket.
Thanks !!.
