### ISSUE TITLE
Getting warning "Undefined property: Drush\Commands\acsf_tools\AcsfToolsCommands::$aliasRecord AcsfToolsUtils.php:44"

### ISSUE THREAD

**Issue by joshirohit100** [acquia/acsf-tools#162]
Steps to re-produce -

Run the command `drush acsf-tools-dump -v` and notice the warning.

At line https://github.com/acquia/acsf-tools/blob/10.x-dev/AcsfToolsUtils.php#L44

acsf-tools version using - 10
Drupal - 9.4
PHP - 8

Issue looks like alias is not set (seems because https://github.com/acquia/acsf-tools/blob/10.x-dev/AcsfToolsCommands.php#L638 
  **::aliasValidate()** is not called for DB dump command) 

This change seems introduced in https://github.com/acquia/acsf-tools/pull/154

**Comment by vbouchet31** [comment]
As per the title of #154 I don't think any other command that ml, mlc and list are supposed to "benefit" from the local-alias feature.
```
if ($this->aliasRecord && $this->aliasRecord->isLocal() && !$this->checkAcsfFunction('gardens_site_data_load_file')) {
  return $sites;
}
```

should probably be replaced by
```
if (isset($this->aliasRecord) && $this->aliasRecord->isLocal() && !$this->checkAcsfFunction('gardens_site_data_load_file')) {
  return $sites;
}
```

**Comment by Supreetam09** [comment]
Raised PR [https://github.com/acquia/acsf-tools/pull/163](https://github.com/acquia/acsf-tools/pull/163) to fix this following comment from @vbouchet31

**Comment by vbouchet31** [comment]
Thanks @Supreetam09 I merged the PR so it is available on latest dev.
