### ISSUE TITLE
Drupal 10 support.

### ISSUE THREAD

**Issue by angelHarizanov** [acquia/acsf-tools#164]
acsf-tools has a dependency on "symfony/yaml": "^3.0 | ^4.0" but Drupal 10 depends on Symfony ^6. Are there any plans for a release for D10 and Drush 11+ for that matter?

**Comment by vbouchet31** [comment]
Hi @angelHarizanov. Thanks for reporting. Unfortunately, there is no "plan" as it is not an official "product" or "package". We should make it clear in the README. I will try to work on upgrading in the next days/weeks but feel free to raise a pull request if you did something already.

**Comment by vbouchet31** [comment]
Hi @angelHarizanov. I release a D10 / Drush 11 version. I gave a quick try on the most common commands and it is working as expected. I am closing this issue. Feel free to reopen or raise new one if you face any issue.

https://github.com/acquia/acsf-tools/releases/tag/11.0.0

**Comment by angelHarizanov** [comment]
Thanks a lot @vbouchet31
