### ISSUE TITLE
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in

### ISSUE THREAD

**Issue by yasenivanovffw** [acquia/acsf-tools#168]
**Describe the bug**
Using PHP 8.2 with ACSF Tools 11.X on Acquia Cloud Site Factory throws the following error, when some error should be outputted during post site install:

`Using ${var} in strings is deprecated, use {$var} instead AcsfToolsBackgroundTasksCommands.php:246\n \u001b[37;46;1m[info]\u001b[39;49;22m Using ${var} in strings is deprecated, use {$var} instead AcsfToolsBackgroundTasksCommands.php:246`

**Comment by vbouchet31** [comment]
Thanks for reporting. I fixed it one 11.x-dev and created a new release 11.0.1.
