### ISSUE TITLE
ACSF-Tools doesn't work from ~/.drush global drush folder...

### ISSUE THREAD

**Issue by eguerin-ucsf** [acquia/acsf-tools#43]
None of this is possible in global drush installation.   When you composer install the dependencies, it is still missing the G folder from the docroot.   It needs this for the gardens_site_data_load_file() function.   The instructions on the github readme are wrong here.

All the paths have to be updated or changed to run from your global drush folder, however things still don't work even after fixing most pathing issues.

* move the vendor directory from the acsf-tools folder to the .drush folder.
* Edit line 4 of the acsf_tools.aliases.drushrc.php file
* replacing  '/../../vendor/autoload.php' with  '/../vendor/autoload.php'  basically changing the vendor path so its not in my personal users directory.
* edit acsf_tools_generate_aliases.drush.inc removing one up path /../  from the line 57 
$new_file = $realpath . '/../site-aliases/' . $new_alias_filename;
* create the site-aliases folder in the .drush folder
* edit your acsf_tools_config.yml
* run the drush sfa command

No results come from the live site.

**Comment by sdelbosc** [comment]
@eguerin-ucsf I understand that you want to install acsf-tools command in ~/.drush folder. Is that correct? If yes, may I ask why? Because usually this ends up in drush/Commands/acsf_tools/ at the same level as your home folder and I haven't felt the need to move it elsewhere so far.
