### ISSUE TITLE
Support ACSF stacks

### ISSUE THREAD

**Issue by seanhamlin** [acquia/acsf-tools#5]
This tool currently assumes a single webserver and sitename. This is not the case for all customers.

**Comment by msherron** [comment]
Hi @seanhamlin - this probably exposes a gap in my ACSF knowledge around the Stacks feature. Doesn't each Stack get its own Repository (and therefore would have different configured `site_id`s)? When developing locally, are Stacks treated as separate installs (with separate docroots)? If the answer is yes to both, then this should work as is, unless I'm missing something. Maybe you an I could get together sometime and you can show me where you're running into an issue.

**Comment by sherakama** [comment]
We have three stacks and the assumption of stack `01` is not correct. Sometimes we want to run on stack `02`

**Comment by vbouchet31** [comment]
I don't think there is still assumption on the stack id (01, 02, ...) anymore at least in the main commands (ml, dump, restore, ...)

Regarding supporting stack, I am not sure it makes sense given each stack may run a different code base. It is even considered a different subscription in acquia cloud so it would be complex to execute the command on all the stacks.

**Comment by sdelbosc** [comment]
I agree with Vincent on the fact that I have not seen any dependency with stacks in the commands I used frequently (on a project with 5 stacks)
Does anyone have any example of broken command in multi stacks or tangles context?
