### ISSUE TITLE
drush acsf-tools-ml sqlq "select count(uid) from users;" command doesn't work

### ISSUE THREAD

**Issue by stutee90** [acquia/acsf-tools#67]
Hi Team,

We are trying to run the command `drush acsf-tools-ml sqlq "select count(uid) from users;" ` at our end. But it is not working. Also no other select queries are working either.

```
  Too many arguments, expected arguments "command" "query", provided arguments "command" "query".


sql:query [--result-file [RESULT-FILE]] [--file FILE] [--extra EXTRA] [--db-prefix] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--database [DATABASE]] [--target [TARGET]] [--db-url DB-URL] [--xh-link XH-LINK] [--druplicon] [--notify] [--] <command> [<query>]
```
I have checked the drush sqlq "select count(uid) from users;" --uri=example.com, it works fine.

Could you please have a look and let us know what might be the issue.

**Comment by sdelbosc** [comment]
This is a consequence of the move to drush 9. The appropriate syntax is: drush acsf-tools-ml 'sqlq "select count(uid) from users;"'

**Comment by stutee90** [comment]
Thank you so much @sdelbosc . All the sqlq queries working fine.
