### ISSUE TITLE
Support Drush 10

### ISSUE THREAD

**Issue by mpodorov** [acquia/acsf-tools#71]
Is there a plan to support Drush 10?
Several drush_* functions should be replaced by the OOP code.

**Comment by sdelbosc** [comment]
Hi @mpodorov,

Some people started working on it in https://github.com/acquia/acsf-tools/pull/84.
Note that this is still WIP.

**Comment by benjifisher** [comment]
The pull request #84 has been merged. Should this issue be updated? Is it fixed?

**Comment by vbouchet31** [comment]
I would say basic support of Drush 10 is here. I confirm main commands (at least my main commands) ml, dump and restore are working. However, there is still work to do given (for example) acsf-tools-ml does not show the message from individual site (drush acsf-tools-ml cr won't display anything else than "=> Running command on xxxxxxxxx"

**Comment by stefan-fuchsberger** [comment]
My recommendation is to add the appropriate drush version as a requirement in composer.json.

Me, I'm using BLT which includes 9.x branch of acst-tools but on the same BLT the drush requirement is set to either ^9.5.0 or ^10.2.2. I ended up with acsf-tools 9.x and drush 10.3.4

Sure I can fix this myself just requiring the correct drush version on root level, but still it would be good to have it here as well.

**Comment by vbouchet31** [comment]
@stefan-fuchsberger I raised https://github.com/acquia/acsf-tools/pull/109.

**Comment by sdelbosc** [comment]
@stefan-fuchsberger #109 got merged. Feel free to reopen if you face any issue.
