### ISSUE TITLE
Command `acsf-tools:ml` permits operations on unavailable sites

### ISSUE THREAD

**Issue by dooleymatt** [acquia/acsf-tools#87]
**Problem:**
Executing `drush @alias acsf-tools:ml command` will execute the passed in command against all sites returned from `gardens_site_data_load_file()`. Depending on the drush command being executed, this can be problematic if any of the sites returned from that function are in a state where they cannot properly handle the command that is passed in. 

**Proposed resolution:**
For each site returned from `gardens_site_data_load_file()` there is a `flags` array which contains several indicators of a site's current status. To prevent the execution of drush commands against a site which is not fully available, there should be a check for the `access_restricted` and `operation` flags to determine if the availability of a site.

**Comment by sdelbosc** [comment]
This has been handled in the prs listed above
